#!/bin/bash

#### Message Type ####
## Select which severity level dialog you want to display
## low = 1, mid = 2, high = 3
protectSeverity=2

#### Jamf School Static Group IDs ####
### Enter the groupId of the low, mid & high groups from Jamf School
lowGroupId= ## INSERT GROUP ID ##
midGroupId= ## INSERT GROUP ID ##
highGroupId= ## INSERT GROUP ID ##

#### No Code/Low Code platform webhook URL ####
### HTTP Endpoint to trigger the device removal from the static group ###
webhookURL= ### INSERT USL INCLOSED IN " " ###

##### Static Variables #####
dialogPath=/usr/local/bin/dialog
serialNumber=$(ioreg -l | grep IOPlatformSerialNumber | cut -d '"' -f 4)


#### Functions ####

groupRemoval(){
	curl -H "Content-Type: application/json" -d '{ "code": 200, "device": { "serialNumber": "'$serialNumber'", "groupId": "'$groupId'" }}' ''$webhookURL''
}

low_severity(){
	$dialogPath \
	--notification \
	--title "Whoopsie" \
	--message "You've just done something that has raised a small security concern. Please be careful on this school owned machine."
}

mid_severity(){
	$dialogPath \
	--big \
	--ontop \
	--title "Whoopsie" \
	--message "You've just done something that has raised a security concern. Please be careful on this school owned machine. \n\n Please take a second to review the school computer usage policy below" \
	--helpmessage "This is a message generated by IT. If you think that your device is behaving sus, get in touch with IT through the normal procedure" \
	--icon /Applications/JamfProtect.app \
	--overlayicon caution \
	--infobox "### Jamf Academy \n\n School way, Newcastle Under Lyme, Staffs, ST51JS" \
	--webcontent https://jamfnation.live/odcf/jnuc_agreement.pdf \
	--checkbox "I Agree",enableButton1 \
	--button1disabled
}

high_severity(){
	$dialogPath \
	--big \
	--blurscreen \
	--title "Whoopsie" \
	--alignment centre \
	--message "You've just done a **BIG WHOOPSIE**. \n\n Due to secuirty concerns the school IT dept have locked down your machine \n\n Please contact the IT dept _imediately_ on 01234 98776 or by visiting the support desk" \
	--alignment center \
	--helpmessage "This is a message generated by IT. If you think that your device is behaving sus, get in touch with IT through the normal procedure" \
	--icon /Applications/JamfProtect.app \
	--overlayicon caution \
	--infobox "### Jamf Academy \n\n School way, School City, UK, ST51JS" \
	--button1text none \
	--quitkey k \
	--image https://content.imageresizer.com/images/memes/Homer-Panic-meme-3.jpg
}

#### Script Locgic ####

if [ $protectSeverity == 1 ]; then
	groupId=$lowGroupId
	low_severity
	groupRemoval
elif [ $protectSeverity == 2 ]; then
	groupId=$midGroupId
	mid_severity
	groupRemoval
elif [ $protectSeverity == 3 ]; then
	groupId=$highGroupId
	high_severity
	groupRemoval
else
	echo "something went wrong"
fi
